server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

# 2칸 공백, 탭키 절대 사용 금지!
# 로그 설정 (개발환경용)
# 로그 레벨의 개념
# ERROR > WARN > INFO > DEBUG > TRACE
logging:
  level:
    root: INFO           # 모든 라이브러리는 INFO 이상만 출력
    com.example: DEBUG   # 내 프로젝트는 DEBUG 이상 모두 출력

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    #발신자 계정
    username: ${GMAIL_USERNAME}
    #주의: 자신의 메일 비밀번호아님 SMTP 앱 비밀번호임
    password: ${GMAIL_APP_PASSWORD}

    properties:
      mail:
        smtp:
          # SMTP 서버 인증 활성화 (ID/PW 검사 여부)
          auth: true
          # START TLS (보안 연결)
          starttls:
            # 비 암호화 연결을 암호화 연결(TLS)로 승격 활성화 (권장 사항 = 무조건)
            enable: true
            required: true
          # 타임아웃설정 - 서버 간 통신 기준 (우리와 메일서버간)
          # 소켓 연결 제한 시간 (단위 밀리초 1000ms = 1s)
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  servlet:
    multipart:
      enabled: true             # 파일 업로드 활성화
      max-file-size: 10MB       # 개별 파일 최대 크기
      max-request-size: 10MB    # 전체 요청 최대 크기

  # 데이터베이스 연결 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root

  # H2 데이터베이스 웹 콘솔 활성화 (개발용)
  # localhost:8080/h2-console로 접속 가능
  h2:
    console:
      enabled: true

  # 초기 데이터 로딩 설정
  sql:
    init:
      # 2.5 이상 버전부터 명시를 해야 insert 처리 됨
      mode: never
      # 애플리케이션 시작시 실행할 SQL 파일 위치
      data-locations:
        - classpath:db/data.sql

  # JPA 설정
  jpa:
    hibernate:
      # create: 애플리케이션 시작시 테이블을 새로 생성
      # 기존 데이터는 모두 삭제됨 (개발용)
      ddl-auto: update
    # SQL 쿼리를 콘솔에 출력 (개발용 디버깅)
    show-sql: true
    properties:
      hibernate:
        # SQL 쿼리를 보기 좋게 포맷팅
        format_sql: true
        # N + 1 문제 해결 중 하나: LAZY 로딩 시 연관된 엔티티를 배치로 한 번에 가져오기
        # 게시글 목록 조회 시 만약 (username 필요 시)
        # 배치로 묶어서 한 번에 가져옴 (IN 쿼리 사용)
        default_batch_fetch_size: 100
    # data.sql 파일을 Hibernate 초기화 이후에 실행
    defer-datasource-initialization: true
    # Open Session in View를 false로 설정
    # - true (기본값) 뷰 랜더링 까지 세션 유지 (LAZY 로딩 가능)
    # - false : 트랜잭션 종료 시 세션 종료 (LAZY 로딩 불가, 명시적 조회 필요(트리거))
    # - false 설정 시 Service 에서 필요한 데이터를 모두 조회하고 DTO로 변환 해야 함
    open-in-view: false

# 최초 파라미터 선언
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}

tenco:
  key: ${TENCO_KEY}